# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3a1618ccb17e15ccf3aa03d94dd1c20f76df750c90bb046623a272e0bbd21fcf6d7a3140f78c09807bb1606483e7917684fbf0a35f1930bc11569da3ee8d8db

test:
  secret_key_base: 957f644e993253e72e030bc4eae24fc645620cc78cdfd50be6222edf9d8755dd8d950156b7a0374d8402a520873a7705055b0e9bab9715bc5d9cc74dd3f5d444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  twitter_api_id: <%= ENV['TWITTER_APP_ID'] %>
  twitter_apu_secret: <%= ENV['TWITTER_SECRET'] %>
  #google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  #google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  #foursquare_consumer_key: <%= ENV["FOURSQUARE_CLIENT_ID"] %>
  #foursquare_consumer_secret: <%= ENV["FOURSQUARE_CLIENT_SECRET"] %>


FACEBOOK_APP_ID
  facebook_secret: FACEBOOK_SECRET
  twitter_api_id: TWITTER_APP_ID
  twitter_apu_secret: TWITTER_SECRET